### ISSUE TITLE
[Anon] Knight Household: Questoris Knight Crusader missing the option for rocket pods, and Questoris Knight Gallant missing the option to swap out its chainsword for another gauntlet.

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/Horus-Heresy-Legions-Imperialis#122]
**Problem:**
Questoris Knight Crusader missing the option for rocket pods, and Questoris Knight Gallant missing the option to swap out its chainsword for another gauntlet.

**Expected:**
It should be possible to mount rocket pods on all Questoris Knights, and swap out chainswords for thunderstrike gauntlets.

 **Additional Info:**
Core Rulebook, page 206 (the datasheet for Questoris Knight Banner).

**List:** https://www.newrecruit.eu/app/list/FZAOW

**Comment by Dunamis55** [comment]
The Crusader can only take rocket pods if equipped with a battlecannon.

**Comment by WeissRaben90** [comment]
Are you implying that a Crusader with Gatling Cannon shouldn't be able to take the pods? Because I can see nothing that implies such a thing - the "loadouts" are the classes of Questoris, not the specific options inside each loadout. The asterisk is there to forbid the Magaera/Styrix from getting the pods.
