### ISSUE TITLE
[Anon] Bug report: Solar Auxilia.catz Heavy Armour detachments seem to double points values

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/Horus-Heresy-Legions-Imperialis#26]
**File:** Solar Auxilia.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** The solar auxilia heavy Armour detachments seem to double points values when running 2 separate detachments. If you select 2 detachments of 1 Baneblade each, it reports a points cost of 380, not 200.  Adding 1 more Baneblade each brings up the total to 710, not 380.

**Comment by TrentBartlem** [comment]
Yeah, it seems to count all the models in the formation instead of just the number of models in the detachment (but not other formations)

**Comment by CBLimerick** [comment]
It’s not just the Heavy Armour Detachments. In the Solar Auxilia Armoured Company, under battle tank if you add a Lemon Russ Strike Squadron, then the cost of the Malcador Tank Squadron cost go out. It looks like it starts to add each tank to the base cost of the Malcador Tank Squadron rather than leaving the 2 free under the 165 base cost.

**Comment by TrentBartlem** [comment]
True. Russes aren't affected because they have a different way of adding unit
