### ISSUE TITLE
Giving a Command Squad a Rhino as dedicated transport makes the unit cost -135 points

### ISSUE THREAD

**Issue by krobb001** [BSData/Horus-Heresy-Legions-Imperialis#29]
Not sure what's up with the calculations behind the additional cost of dedicated transports

**Comment by krobb001** [comment]
just noticed the overall cost in the list builder itself is correct, but the unit shows up as costing -135 points when it actually contributes 35 points to the list total as expected

**Comment by Dunamis55** [comment]
Are you definitely using the latest data? If so, are you able to add a screenshot of the issue please?

**Comment by krobb001** [comment]
I was on 1.0.3 but I updated to 1.0.5 just now, however I am still seeing the issue (on both new and existing rosters)

![Screenshot_20231218_123003](https://github.com/BSData/Horus-Heresy-Legions-Imperialis/assets/89421223/374ea726-8925-4520-acdd-78e1d7ba6a52)

**Comment by Dunamis55** [comment]
Weird - seems it's an issue with the BattleScribe mobile app rather than the data - it's fine on the desktop app and in NewRecruit. Best solution would be to switch over to using [NewRecruit](https://www.newrecruit.eu/) instead of BattleScribe, as the app won't get fixed.

Closing the issue, as there's no way to fix it.
