### ISSUE TITLE
[Anon] Legiones Astartes: There’s always an error saying I need a dedicated transport, when I want to use other transports 

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/Horus-Heresy-Legions-Imperialis#97]
**Problem:**
There’s always an error saying I need a dedicated transport, when I want to use other transports 

**Expected:**
No error saying I don’t have enough dedicated transports, as I’m using transport in the air support slot 

**List:** https://www.newrecruit.eu/app/list/nz2ux
**Unit:** Legion Tactical Detachment[2], id: e552-7189-ccb5-1922

**Comment by TrentBartlem** [comment]
There is an issue where non-dedicated transports are not counted for the aerial assault formation. That's tracked in #109. 

However in your case, you have checked the 'dedicated transport' option for many of your infantry detachments, but haven't actually chosen one of the options, which is why it's complaining.
